# Generated by Django 5.0.1 on 2024-01-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_karbar_date_of_birth_karbar_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='karbar',
            name='sid',
            field=models.CharField(default='1111111111', max_length=10, unique=True, verbose_name='Student/Professor ID'),
        ),
        migrations.AlterField(
            model_name='karbar',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='karbar',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
