# Generated by Django 5.0.1 on 2024-01-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_karbar_sid_alter_karbar_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karbar',
            name='sid',
            field=models.CharField(default='1111111111', max_length=10, verbose_name='Student/Professor ID'),
        ),
    ]
