# Generated by Django 5.0.1 on 2024-01-10 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.karbar'),
        ),
    ]
