# Generated by Django 5.0.1 on 2024-01-10 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='classmates',
            field=models.ManyToManyField(blank=True, related_name='classmates', to='users.karbar'),
        ),
        migrations.AddField(
            model_name='claim',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='claim',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.karbar'),
        ),
    ]
